// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProxy(arg1) {
  return window['go']['main']['App']['AddProxy'](arg1);
}

export function DeleteProxy(arg1) {
  return window['go']['main']['App']['DeleteProxy'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConnState() {
  return window['go']['main']['App']['GetConnState']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetNetworkStats() {
  return window['go']['main']['App']['GetNetworkStats']();
}

export function GetProxyStates() {
  return window['go']['main']['App']['GetProxyStates']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ServiceRunning() {
  return window['go']['main']['App']['ServiceRunning']();
}

export function StartService() {
  return window['go']['main']['App']['StartService']();
}

export function StopService() {
  return window['go']['main']['App']['StopService']();
}

export function ToggleProxy(arg1) {
  return window['go']['main']['App']['ToggleProxy'](arg1);
}

export function UpdateProxy(arg1, arg2) {
  return window['go']['main']['App']['UpdateProxy'](arg1, arg2);
}
