// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {main} from '../models';
import {frpclient} from '../models';

export function AddProxy(arg1:model.ProxyItem):Promise<void>;

export function DeleteProxy(arg1:string):Promise<void>;

export function GetConfig():Promise<model.ClientAppConfig>;

export function GetConnState():Promise<string>;

export function GetLogs():Promise<Array<string>>;

export function GetNetworkStats():Promise<main.NetworkStats>;

export function GetProxyStates():Promise<Array<frpclient.ProxyState>>;

export function SaveConfig(arg1:model.ClientAppConfig):Promise<void>;

export function ServiceRunning():Promise<boolean>;

export function StartService():Promise<void>;

export function StopService():Promise<void>;

export function ToggleProxy(arg1:string):Promise<void>;

export function UpdateProxy(arg1:string,arg2:model.ProxyItem):Promise<void>;
