// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetProxies() {
  return window['go']['main']['App']['GetProxies']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function OpenDashboard() {
  return window['go']['main']['App']['OpenDashboard']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ServiceRunning() {
  return window['go']['main']['App']['ServiceRunning']();
}

export function StartService() {
  return window['go']['main']['App']['StartService']();
}

export function StopService() {
  return window['go']['main']['App']['StopService']();
}
