// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {frpserver} from '../models';

export function GetConfig():Promise<model.ServerAppConfig>;

export function GetLogs():Promise<Array<string>>;

export function GetProxies():Promise<Array<frpserver.ProxyBrief>>;

export function GetStats():Promise<frpserver.Stats>;

export function OpenDashboard():Promise<void>;

export function SaveConfig(arg1:model.ServerAppConfig):Promise<void>;

export function ServiceRunning():Promise<boolean>;

export function StartService():Promise<void>;

export function StopService():Promise<void>;
